---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-jetbrains-com-v1beta1-teamcity
  failurePolicy: Fail
  name: mv1beta1teamcity.kb.io
  rules:
  - apiGroups:
    - jetbrains.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - teamcities
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-jetbrains-com-v1alpha1-teamcity
  failurePolicy: Fail
  name: mv1alpha1teamcity.kb.io
  rules:
  - apiGroups:
    - jetbrains.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - teamcities
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-jetbrains-com-v1beta1-teamcity
  failurePolicy: Fail
  name: vv1beta1teamcity.kb.io
  rules:
  - apiGroups:
    - jetbrains.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - teamcities
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-jetbrains-com-v1alpha1-teamcity
  failurePolicy: Fail
  name: vv1alpha1teamcity.kb.io
  rules:
  - apiGroups:
    - jetbrains.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - teamcities
  sideEffects: None
