# permissions for end users to view teamcities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: teamcity-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teamcity-operator
    app.kubernetes.io/part-of: teamcity-operator
    app.kubernetes.io/managed-by: kustomize
  name: teamcity-viewer-role
rules:
- apiGroups:
  - jetbrains.com
  resources:
  - teamcities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jetbrains.com
  resources:
  - teamcities/status
  verbs:
  - get
