apiVersion: jetbrains.com/v1beta1
kind: TeamCity
metadata:
  labels:
    app.kubernetes.io/name: teamcity #this labels will be ignored because it tries to override a default one
    foo: bar #this custom label will be applied
  name: teamcity-sample-beta
  namespace: default
  finalizers:
    - "teamcity.jetbrains.com/finalizer"
spec:
  image: jetbrains/teamcity-server
  replicas: 1
  env:
    AWS_DEFAULT_REGION: "eu-west-1"
  requests:
    cpu: "1000m"
    memory: "2500Mi"
  dataDirVolumeClaim:
    name: teamcity-node-volume1
    volumeMount:
      name: teamcity-node-volume1
      mountPath: /storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
