apiVersion: jetbrains.com/v1beta1
kind: TeamCity
metadata:
  name: teamcity-sample-with-ingress
  namespace: default
  finalizers:
    - "teamcity.jetbrains.com/finalizer"
spec:
  image: jetbrains/teamcity-server
  mainNode:
    name: main-node
    spec:
      env:
        AWS_DEFAULT_REGION: "eu-west-1"
      requests:
        cpu: "900m"
        memory: "1512Mi"
  dataDirVolumeClaim:
    name: teamcity-node-volume1
    volumeMount:
      name: teamcity-node-volume1
      mountPath: /storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  persistentVolumeClaims:
    - name: teamcity-node-config-dir
      volumeMount:
        name: teamcity-node-config-dir
        mountPath: /storage/config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  serviceList:
    - name: tc-sample-for-ingress
      spec:
        selector:
          app.kubernetes.io/name: teamcity-sample-with-ingress
          app.kubernetes.io/component: teamcity-component
          app.kubernetes.io/part-of: teamcity
        ports:
          - protocol: TCP
            port: 8111
            targetPort: 8111
        clusterIP: None
  ingressList:
  - name: tc-ingress
    annotations: {}
    spec:
      ingressClassName: nginx
      rules:
        - host: tc-sample.myteamcity.com
          http:
            paths:
              - backend:
                  service:
                    name: tc-sample
                    port:
                      number: 8111
                pathType: ImplementationSpecific
