apiVersion: jetbrains.com/v1beta1
kind: TeamCity
metadata:
  labels:
    app.kubernetes.io/name: teamcity #this labels will be ignored because it tries to override a default one
    foo: bar #this custom label will be applied
  name: teamcity-sample-with-secondary-node
  namespace: default
  finalizers:
    - "teamcity.jetbrains.com/finalizer"
spec:
  image: jetbrains/teamcity-server
  startupPropertiesConfig:
    teamcity.startup.maintenance: "false"
    teamcity.licenseAgreement.accepted: "true"
    teamcity.firstStart.setupAdmin.enabled: "false"
    teamcity.superUser.token: "token123"
  databaseSecret:
    secret: database-properties
  dataDirVolumeClaim:
    name: teamcity-node-volume1
    volumeMount:
      name: teamcity-node-volume1
      mountPath: /storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  mainNode:
    name: main-node
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      requests:
        cpu: "1000m"
        memory: "2500Mi"
      responsibilities: [ "MAIN_NODE", "CAN_PROCESS_USER_DATA_MODIFICATION_REQUESTS"]
  secondaryNodes:
    - name: secondary-node
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      spec:
        requests:
          cpu: "1000m"
          memory: "2500Mi"
        responsibilities: ["CAN_PROCESS_BUILD_MESSAGES", "CAN_CHECK_FOR_CHANGES", "CAN_PROCESS_BUILD_TRIGGERS", "CAN_PROCESS_USER_DATA_MODIFICATION_REQUESTS"]
