#file: noinspection YAMLSchemaValidation
apiVersion: v1
data:
  teamcity-startup.properties: |+
    teamcity.startup.maintenance=false
    teamcity.licenseAgreement.accepted=true
    teamcity.firstStart.setupAdmin.enabled=false
    teamcity.superUser.token=token123
kind: ConfigMap
metadata:
  name: startup-properties
  namespace: default
---
apiVersion: jetbrains.com/v1alpha1
kind: TeamCity
metadata:
  labels:
    app.kubernetes.io/name: teamcity
    app.kubernetes.io/instance: teamcity
    app.kubernetes.io/part-of: teamcity-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teamcity-operator
  name: teamcity-sample-with-startup-properties
  namespace: default
  finalizers:
    - "teamcity.jetbrains.com/finalizer"
spec:
  image: jetbrains/teamcity-server
  replicas: 1
  startupPropertiesConfigMap: "startup-properties"
  requests:
    cpu: "1000m"
    memory: "2500Mi"
  persistentVolumeClaims:
    - name: teamcity-node-data-dir
      volumeMount:
        name: teamcity-node-data-dir
        mountPath: /storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - name: teamcity-node-config-dir
      volumeMount:
        name: teamcity-node-config-dir
        mountPath: /storage/config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi