#file: noinspection YAMLSchemaValidation
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS teamcity;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
      containers:
        - image: mysql:8
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
---
#based on database.properties
apiVersion: v1
data:
  database.properties: Y29ubmVjdGlvblVybD1qZGJjOm15c3FsOi8vbXlzcWwuZGVmYXVsdDozMzA2L3RlYW1jaXR5CmNvbm5lY3Rpb25Qcm9wZXJ0aWVzLnVzZXI9cm9vdApjb25uZWN0aW9uUHJvcGVydGllcy5wYXNzd29yZD1wYXNzd29yZApjb25uZWN0aW9uUHJvcGVydGllcy5zb2NrZXRUaW1lb3V0PTkwMDAwMAo=
kind: Secret
metadata:
  name: database-properties
---
apiVersion: jetbrains.com/v1beta1
kind: TeamCity
metadata:
  labels:
    app.kubernetes.io/name: teamcity
    app.kubernetes.io/instance: teamcity-sample
    app.kubernetes.io/part-of: teamcity-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teamcity-operator
  name: teamcity-sample-full
  namespace: default
  finalizers:
    - "teamcity.jetbrains.com/finalizer"
spec:
  image: jetbrains/teamcity-server
  replicas: 1
  databaseSecret:
    secret: database-properties
  startupPropertiesConfig:
    teamcity.startup.maintenance: "false"
    teamcity.licenseAgreement.accepted: "true"
    teamcity.firstStart.setupAdmin.enabled: "false"
    teamcity.superUser.token: "token123"
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: [ 'sh', '-c', "echo Hello" ]
  env:
    AWS_DEFAULT_REGION: "eu-west-1"
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  xmxPercentage: 95
  requests:
    cpu: "400m"
    memory: "1000Mi"
  readinessEndpoint:
    path: "/healthCheck/ready"
    scheme: HTTP
    port: 8111
  healthEndpoint:
    path: "/healthCheck/ready"
    scheme: HTTP
    port: 8111
  livenessProbeSettings:
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 1
  readinessProbeSettings:
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 1
  startupProbeSettings:
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 1
  dataDirVolumeClaim:
    name: teamcity-node-volume1
    volumeMount:
      name: teamcity-node-volume1
      mountPath: /storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  persistentVolumeClaims:
    - name: teamcity-node-config-dir
      volumeMount:
        name: teamcity-node-config-dir
        mountPath: /storage/config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  serviceList:
    - name: tc-sample
      spec:
        selector:
          app.kubernetes.io/component: teamcity
          app.kubernetes.io/name: teamcity-sample-full
          app.kubernetes.io/part-of: teamcity
        ports:
          - protocol: TCP
            port: 8111
            targetPort: 8111
        clusterIP: None
  ingressList:
    - name: tc-ingress
      annotations: { }
      spec:
        ingressClassName: nginx
        rules:
          - host: jenkins.cloud
            http:
              paths:
                - backend:
                    service:
                      name: tc-sample
                      port:
                        number: 8111
                  pathType: ImplementationSpecific
