#file: noinspection YAMLSchemaValidation
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS teamcity;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
      containers:
        - image: mysql:8
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
---
#based on database.properties
apiVersion: v1
data:
  connectionProperties.password: cGFzc3dvcmQ=
  connectionProperties.user: cm9vdA==
  connectionUrl: amRiYzpteXNxbDovL215c3FsLmRlZmF1bHQ6MzMwNi90ZWFtY2l0eQ==
kind: Secret
metadata:
  name: database-properties
---
apiVersion: jetbrains.com/v1beta1
kind: TeamCity
metadata:
  labels:
    app.kubernetes.io/name: teamcity
    app.kubernetes.io/instance: teamcity-sample
    app.kubernetes.io/part-of: teamcity-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teamcity-operator
  name: teamcity-sample-full
  namespace: default
  finalizers:
    - "teamcity.jetbrains.com/finalizer"
spec:
  image: jetbrains/teamcity-server
  databaseSecret:
    secret: database-properties
  startupPropertiesConfig:
    teamcity.startup.maintenance: "false"
    teamcity.firstStart.setupAdmin.enabled: "false"
    teamcity.superUser.token: "token123"
  xmxPercentage: 95
  readinessEndpoint:
    path: "/healthCheck/ready"
    scheme: HTTP
    port: 8111
  healthEndpoint:
    path: "/healthCheck/ready"
    scheme: HTTP
    port: 8111
  mainNode:
    name: main-node
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: [ 'sh', '-c', "echo Hello" ]
      responsibilities: [ "MAIN_NODE", "CAN_PROCESS_USER_DATA_MODIFICATION_REQUESTS" ]
      env:
        AWS_DEFAULT_REGION: "eu-west-1"
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      requests:
        cpu: "900m"
        memory: "1512Mi"
      livenessProbeSettings:
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 20
        initialDelaySeconds: 60
        timeoutSeconds: 1
      readinessProbeSettings:
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 20
        initialDelaySeconds: 60
        timeoutSeconds: 1
      startupProbeSettings:
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 20
        initialDelaySeconds: 60
        timeoutSeconds: 1
  secondaryNodes:
    - name: secondary-node
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      spec:
        requests:
          cpu: "900m"
          memory: "1512Mi"
        responsibilities: ["CAN_PROCESS_BUILD_MESSAGES", "CAN_CHECK_FOR_CHANGES", "CAN_PROCESS_BUILD_TRIGGERS", "CAN_PROCESS_USER_DATA_MODIFICATION_REQUESTS"]
    - name: secondary-node-1
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      spec:
        requests:
          cpu: "1000m"
          memory: "2500Mi"
        responsibilities: [ "CAN_PROCESS_BUILD_MESSAGES", "CAN_CHECK_FOR_CHANGES", "CAN_PROCESS_BUILD_TRIGGERS", "CAN_PROCESS_USER_DATA_MODIFICATION_REQUESTS" ]
  dataDirVolumeClaim:
    name: datadir
    volumeMount:
      name: datadir
      mountPath: /storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  persistentVolumeClaims:
    - name: additional-volume
      volumeMount:
        name: additional-volume
        mountPath: /storage/config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  serviceList:
    - name: tc-sample
      spec:
        selector:
          app.kubernetes.io/component: teamcity-server
          app.kubernetes.io/name: teamcity-sample-full
          app.kubernetes.io/part-of: teamcity
        ports:
          - protocol: TCP
            port: 8111
            targetPort: 8111
        clusterIP: None
  ingressList:
    - name: tc-ingress
      annotations: { }
      spec:
        ingressClassName: nginx
        rules:
          - host: jenkins.cloud
            http:
              paths:
                - backend:
                    service:
                      name: tc-sample
                      port:
                        number: 8111
                  pathType: ImplementationSpecific
