apiVersion: jetbrains.com/v1alpha1
kind: TeamCity
metadata:
  labels:
    app.kubernetes.io/name: teamcity
    app.kubernetes.io/instance: teamcity
    app.kubernetes.io/part-of: teamcity-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teamcity-operator
  name: teamcity-with-startup-properties
  namespace: default
  finalizers:
    - "teamcity.jetbrains.com/finalizer"
spec:
  image: jetbrains/teamcity-server
  replicas: 1
  startupPropertiesConfig:
    teamcity.startup.maintenance: "false"
    teamcity.licenseAgreement.accepted: "true"
    teamcity.firstStart.setupAdmin.enabled: "false"
    teamcity.superUser.token: "token123"
  requests:
    cpu: "400m"
    memory: "1000Mi"
  persistentVolumeClaims:
    - name: teamcity-node-data-dir
      volumeMount:
        name: teamcity-node-data-dir
        mountPath: /storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - name: teamcity-node-config-dir
      volumeMount:
        name: teamcity-node-config-dir
        mountPath: /storage/config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi